public class sampleaddmultcodes {
/*
list<integer> li = new list<integer>{2,4,0,6,7};

integer sum1=0;
for(integer k:li ){
    sum1=sum1+k;
}
system.debug(sum1);

integer mul=1;
for(integer i=0;i<li.size();i++){
     mul=mul*li[i];
    if(li[i]==0){ 
        break;}
    
}
system.debug(mul);

integer summ1=0,summ2=0;
for(integer i=0;i<li.size();i++){
    if(math.mod(li[i],2)==0){ 
        summ1=summ1+li[i];
            }
    else{
       summ2=summ2+li[i]; 
    }
    
}
system.debug(' even  '+summ1 +'   odd   '+summ2);

integer h=0,facto=1;
for(integer i=1;i<=h;i++){
   facto=facto*i;
}
system.debug(facto);

decimal mean=0,ans;
for(integer i=0;i<li.size();i++){
    mean=mean+li[i];
    
}
ans=mean/li.size();
system.debug(ans);


list<integer> li=new list<integer>{2,6,0,4,10,3,8,22};
    li.sort();
system.debug('sort'+li);

system.debug(li[li.size()-3]);

integer sum=0;
for(integer i=0;i<li.size();i++){
    sum=sum+li[i];
}
system.debug(sum);

integer sum1=0;
for(integer i=0;i<=100;i++){
    sum1=sum1+i;
}
system.debug(sum1);
integer facto=1,num=0;
for(integer i=1;i<=num;i++){
    //facto=facto*i;
    facto*=i;
}
system.debug(facto);


list<integer> nli=new list<integer>{55,76,89,200,44,39};
list<integer> evenNums = new List<Integer>();
list<integer> oddNums = new List<Integer>();
    for(integer i=0;i<nli.size();i++){
        if(math.mod(nli[i],2)==0){
          evenNums.add(nli[i]);
            
        }
        else{
            oddNums.add(nli[i]);
             
        }
    }
         system.debug('this are even numbers  ' +evenNums);     
        system.debug('this are odd numbers  ' +oddnums);
*/
}